### ISSUE TITLE
Update for Laravel 5.5?

### ISSUE THREAD

**Issue by sebastiansulinski** [faustbrian/Laravel-Service-Provider#14]
Are you planning to update package to support Laravel 5.5?

**Comment by faustbrian** [comment]
Feel free to send a PR.

**Comment by sebastiansulinski** [comment]
I'm working on the project where this package was used by previous developer.
Are there any breaking changes? If not - can you just update `composer.json` to support Laravel 5.5 ?

**Comment by faustbrian** [comment]
https://github.com/faustbrian/Laravel-Service-Provider/commit/9c88392886ab3e99a1c881bb8e977b9d66ccd0e5
